### PR TITLE
Enable running all specs for each exercise with a compile time flag.

### PR DESCRIPTION
**Pull request by dscottboggs**
This allows a user to run all tests for an exercise by specifying the `RUN_ALL_TESTS` compiler flag, like

```
crystal spec -D RUN_ALL_TESTS
```

Let me know what you think.

### CODE REVIEW

**Comment by mhelmetag** [comment]
Eh, this goes a bit against the exercism mantra of "simple green" (solving the test one case at a time).

I think it also adds to the complexity of the tests. I'd like them to be as simple as possible.

**Comment by dscottboggs** [comment]
TBH I expected some criticism of this... it just seems like we should be able to use a compile time flag to toggle the `pending` tests, like with `-- --ignored` on the Rust track or `-D CMAKE_CXX_FLAGS="-D EXERCISM_RUN_ALL_TESTS` in the C++ track.

I thought about bringing this up as a PR or issue on Crystal itself, but it seems to go against what `pending` is meant to represent. That made me also think of creating a new macro that wraps `pending` or `it` depending, but I couldn't think of what to call it. Something like

```crystal
macro to_be_done(msg, &block)
  {% if flag? :RUN_ALL_TESTS %}
  it {{msg}} {{block.id}}
  {% end %}
end
```

**Comment by dscottboggs** [comment]
I'm going to close this...if someone else thinks its a good idea, perhaps reopen it, but if it's undesirable, that's ok with me too.

**Comment by mhelmetag** [comment]
If there was some way to make this simpler so that the specs look more normal (`it`, `pending`, `etc`), I'd be game.

**Pull request closed without merging**
