### PR TITLE
Add default introductory code example

### PR DESCRIPTION
**Pull request by kytrinyx**
Instead of having logic for a fallback in the backend, we're choosing a
default for the snippet file.

For tracks that have core exercises, we pick the first core exercise.
For tracks without these, we pick the first exercise listed in the config.

Note that we're aiming for 10 lines and a max-width of 40 columns.
This solution has a max-width of 41, so we may want to adjust it.

See https://github.com/exercism/meta/issues/89

### CODE REVIEW

**Comment by kytrinyx** [comment]
I think we could just get rid of the default and hard code the full 'Hello World' string. @mhelmetag - would you have 5 minutes to fix this? (Also how do you not have commit on this repo? Do you want it?)

**Comment by mhelmetag** [comment]
@kytrinyx , I'm fine with either one! I guess that the hardcoded one is the more canonical "Hello, world" example. And I do have commit access on this repo... I have the ability to merge your PRs? Should be fine then.

**Comment by bmulvihill** [comment]
If it is because the line is too long - do we need to specify the type as a String?  It should work using Crystal type inference.

Example: https://play.crystal-lang.org/#/r/2nje

**Comment by bmulvihill** [comment]
@mhelmetag @kytrinyx I removed the Type, I think this should work.

**Comment by kytrinyx** [comment]
> I do have commit access on this repo

Oh, in that case we're fine :)

Thanks for the tweak @bmulvihill.

I'll leave this to the two of you to merge when you're happy.

**Pull request merged**
