### PR TITLE
Wording: Replace function with method

### PR DESCRIPTION
**Pull request by straight-shoota**
Crystal uses methods.

### CODE REVIEW

**Comment by mhelmetag** [comment]
I'll look into this! I believe these readmes are copied from a canonical exercise readme so I'm not sure it's right to edit them.

**Comment by straight-shoota** [comment]
I figured as much. But the correct/idiomatic term for Crystal is method. Crystal *can* expose functions using the `fun` keyword, but what you would expect from normal Crystal code are regular methods defined using `def`.

I don't know whether there is any value in keeping the upstream nomenclature, but for Crystal it would be better to use the term "method"

I'm not sure whether there is some value

**Comment by mhelmetag** [comment]
Sure! I completely agree. I just don't really want to maintain basically patches to the canonical readmes.

I should be able to get back to you with a yay or nay or more info later this week.

**Comment by straight-shoota** [comment]
Is this still open for consideration?

**Comment by mhelmetag** [comment]
Because these are from static readmes, I'd like to keep them the way they are (unedited and from our list of problem metadata).

**Pull request closed without merging**
