### PR TITLE
Refresh flatten_array_spec

### PR DESCRIPTION
**Pull request by chastell**
This refreshes the `flatten_array` spec as per #100.

Cheers from ROSS conf! :tada:

### CODE REVIEW

**Comment by chastell** [comment]
I mean, this was auto-regenerated, yes, but I should’ve fixed the generator to parse the numbers into `Int32`s rather than make it generate `Int64` literals.

**Comment by mhelmetag** [comment]
Oh yeah! Good catch. Thanks for that.

**Comment by mhelmetag** [comment]
Give me a ping whenever you think you're ready and I'll go ahead and merge this. I think parsing to `Int32` is the way to go.

**Comment by martinwalsh** [comment]
Oh, hi! Didn't notice this PR until now ... looked into this a bit and if I've understood correctly the underlying cause is that [`Array#to_s` calls `inspect` for each of its elements](https://github.com/crystal-lang/crystal/blob/master/src/array.cr#L1661), which would seem to explain why string interpolation results in `Int64` literals.

But, I put together a proposal in #112 which provides an exercise generator that uses `JSON.mapping` internally and bypasses the issue by parsing as `Int32`, more or less, as recommended here. The flatten-array exercise is one of the [example implementations in #112](https://github.com/exercism/crystal/commit/16dd07baa347697e857cab70411bc06c4e505d9f). 

Disclaimer: I'm a crystal n00b and hobbyist who would love to contribute something useful back to the wonderful crystal and exercism communities, so feedback on the PR is most welcome!

**Comment by chastell** [comment]
Oh that’s super cool, I actually tentatively thought about migrating the generators to `JSON.mapping`! Feel free to close this PR in lieu of #112 once that gets accepted. :sparkles:

**Pull request closed without merging**
