### PR TITLE
Update interest_is_interesting.cr - camelCase param changed to snake_case

### PR DESCRIPTION
**Pull request by avrame**
targetBalance param for years_before_desired_balance method changed to snake case (target_balance)

### CODE REVIEW

**Comment by meatball133** [comment]
Could you also update the naming in the examplar file?

**Comment by avrame** [comment]
Yeah sure

**Comment by avrame** [comment]
@meatball133 actually, I think the exemplar file already has the parameter in snake_case. Is [this the corresponding place](https://github.com/avrame/crystal/blob/f5d315078aad95e9d19d40893fbcb46d17a634ce/exercises/concept/interest-is-interesting/.docs/instructions.md?plain=1#L52) in the exemplar file?

**Comment by meatball133** [comment]
It is here: https://github.com/exercism/crystal/blob/main/exercises/concept/interest-is-interesting/.meta/src/exemplar.cr

**Review by meatball133 — APPROVED** [review]

**Pull request merged**
