### PR TITLE
Avoid the use of JSON.parse, instead using JSON::Serializable.

### PR DESCRIPTION
**Pull request by dscottboggs**

### CODE REVIEW

**Comment by mhelmetag** [comment]
Besides the merge conflict this looks awesome!

Many thanks!

**Comment by dscottboggs** [comment]
There is a problem -- the test for "forth" (the one exercise I didn't change) is failing now.

**Comment by dscottboggs** [comment]
Nevermind, I see the problem. All the `pending`s got changed to `it`s. Weird.

**Comment by dscottboggs** [comment]
Ok it's ready now.

**Pull request merged**
